### ISSUE TITLE
Error: Module 'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by vvkuryshev** [serengil/deepface#105]
I have the same problem, as described in issue #48. Trying to run pip install tensorflow == 1.9.0 results in an error:
C:\WINDOWS\system32>pip install tensorflow==1.9.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.9.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1)
ERROR: No matching distribution found for tensorflow==1.9.0

Windows10
Python 3.8.

_Originally posted by @vvkuryshev in https://github.com/serengil/deepface/issues/48#issuecomment-703798742_

**Comment by Mahdidrm** [comment]
Same problem. I have checked the code to find any keras and change it to tensorflow.keras but I did not found. @vvkuryshev if you found the answer please tell me. thanks

**Comment by serengil** [comment]
Tensorflow 1.9.0 is available for python 3.6. Please downgrade your python.

**Comment by vvkuryshev** [comment]
Thanks for advise, Sefik. Of course this will work as a temporary solution. But modern versions of python (3.9 is out now) do not support Tensorfow earlier than 2.2. It would be great if deepface worked on TF 2.2+ as well.
