### ISSUE TITLE
Import error in LocallyConnected2D is no longer in TensorFlow >= 2.12.0

### ISSUE THREAD

**Issue by gbaufake** [serengil/deepface#1084]
Currently,

In deepface

``ImportError: cannot import name 'LocallyConnected2D' from 'tensorflow.keras.layers' (/opt/homebrew/lib/python3.12/site-packages/keras/_tf_keras/keras/layers/__init__.py)``

it occurs because LocallyConnected2D layer was removed in TensorFlow 2.x

https://github.com/tensorflow/tensorflow/commit/0908fc936ec4d375a3f8de4bdb7d104b59b0d338#diff-6323a40de9544cd0eb5680defa2981650dbf6743f3c76f92e3ceb9b680d1b3edL97

It works with Tensorflow 2.12 as it stated here: https://stackoverflow.com/questions/78131429/importerror-cannot-import-name-locallyconnected2d-from-tensorflow-keras-laye

**Comment by gbaufake** [comment]
cc @serengil

**Comment by serengil** [comment]
this is already sorted in the source code - not pip version yet

https://github.com/serengil/deepface/blob/master/deepface/basemodels/FbDeepFace.py#L47

**Comment by serengil** [comment]
just published 0.0.86 release

**Comment by gbaufake** [comment]
@serengil Is there any chance to update this to newer versions of TensorFlow?

**Comment by serengil** [comment]
With tf 2.13 or newer, you will not be able to use FbDeepFace model, but you can still use other models in the library.

You still want to use that model?
