### ISSUE TITLE
[BUG]: <AttributeError: module 'deepface.modules.modeling' has no attribute 'build_model'>

### ISSUE THREAD

**Issue by Foundsheep** [serengil/deepface#1589]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [x] I have updated to the latest version of the packages.
- [x] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

v0.0.99

### Python version

3.13.5

### Operating System

Ubuntu 24.04

### Dependencies

absl-py==2.4.0
annotated-doc==0.0.4
annotated-types==0.7.0
anyio==4.12.1
asttokens==3.0.1
astunparse==1.6.3
beautifulsoup4==4.14.3
blinker==1.9.0
certifi==2026.2.25
charset-normalizer==3.4.4
click==8.3.1
comm==0.2.3
debugpy==1.8.20
decorator==5.2.1
deepface==0.0.99
dnspython==2.8.0
email-validator==2.3.0
executing==2.2.1
fastapi==0.135.1
fastapi-cli==0.0.24
fastapi-cloud-cli==0.14.0
fastar==0.8.0
filelock==3.25.0
fire==0.7.1
Flask==3.1.3
flask-cors==6.0.2
flatbuffers==25.12.19
gast==0.7.0
gdown==5.2.1
google-pasta==0.2.0
grpcio==1.78.0
gunicorn==25.1.0
h11==0.16.0
h5py==3.15.1
httpcore==1.0.9
httptools==0.7.1
httpx==0.28.1
idna==3.11
ipykernel==7.2.0
ipython==9.11.0
ipython_pygments_lexers==1.1.1
itsdangerous==2.2.0
jedi==0.19.2
Jinja2==3.1.6
joblib==1.5.3
jupyter_client==8.8.0
jupyter_core==5.9.1
keras==3.13.2
libclang==18.1.1
lightdsa==0.0.3
lightecc==0.0.4
lightphe==0.0.20
lz4==4.4.5
Markdown==3.10.2
markdown-it-py==4.0.0
MarkupSafe==3.0.3
matplotlib-inline==0.2.1
mdurl==0.1.2
ml_dtypes==0.5.4
mpmath==1.3.0
mtcnn==1.0.0
namex==0.1.0
nest-asyncio==1.6.0
numpy==2.4.2
opencv-python==4.13.0.92
opt_einsum==3.4.0
optree==0.19.0
packaging==26.0
pandas==3.0.1
parso==0.8.6
pexpect==4.9.0
pillow==12.1.1
platformdirs==4.9.4
prompt_toolkit==3.0.52
protobuf==7.34.0
psutil==7.2.2
ptyprocess==0.7.0
pure_eval==0.2.3
pydantic==2.12.5
pydantic-extra-types==2.11.0
pydantic-settings==2.13.1
pydantic_core==2.41.5
Pygments==2.19.2
PySocks==1.7.1
python-dateutil==2.9.0.post0
python-dotenv==1.2.2
python-multipart==0.0.22
PyYAML==6.0.3
pyzmq==27.1.0
requests==2.32.5
retina-face==0.0.17
rich==14.3.3
rich-toolkit==0.19.7
rignore==0.7.6
scikit-learn==1.8.0
scipy==1.17.1
sentry-sdk==2.54.0
setuptools==82.0.0
shellingham==1.5.4
six==1.17.0
soupsieve==2.8.3
stack-data==0.6.3
starlette==0.52.1
sympy==1.14.0
tensorboard==2.20.0
tensorboard-data-server==0.7.2
tensorflow==2.20.0
termcolor==3.3.0
tf_keras==2.20.1
threadpoolctl==3.6.0
tornado==6.5.5
tqdm==4.67.3
traitlets==5.14.3
typer==0.24.1
typing-inspection==0.4.2
typing_extensions==4.15.0
urllib3==2.6.3
uvicorn==0.41.0
uvloop==0.22.1
watchfiles==1.1.1
wcwidth==0.6.0
websockets==16.0
Werkzeug==3.1.6
wheel==0.46.3
wrapt==2.1.1
yt-dlp==2026.3.3

### Reproducible example

```Python
deepface_embedding = DeepFace.represent(frame, model_name='Facenet')
```

### Relevant Log Output

40 
   (...)    100         facial features. This field is included only if a `cryptosystem` is provided.
    101 """
    102 resp_objs = []
--> [104](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/djm/workspace/004_cs5939_dds/st_andrews_CS5939_Data_Driven_Systems_A3/cloud/~/workspace/004_cs5939_dds/st_andrews_CS5939_Data_Driven_Systems_A3/.venv_cloud/lib/python3.13/site-packages/deepface/modules/representation.py:104) model: FacialRecognition = modeling.build_model(
    105     task="facial_recognition", model_name=model_name
    106 )
    108 # Handle list of image paths or 4D numpy array
    109 if isinstance(img_path, list):

AttributeError: module 'deepface.modules.modeling' has no attribute 'build_model'

### Expected Result

No error

### What happened instead?

Error happend

### Additional Info

I saw everything works fine in v0.0.98, which I installed somewhere else for a short test about a month ago, and now it doesn't work.
I think it's because of a modification made in the recent release.

**Comment by serengil** [comment]
duplicate - https://github.com/serengil/deepface/issues/1339
